"""
Report generators for HTML, PDF, DOCX, CSV, JSON.
"""

import json
import csv
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Any, Optional

from jinja2 import Environment, FileSystemLoader, select_autoescape
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import inch
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

from claster.core.logger import get_logger
from claster.core.utils import ensure_dir, timestamp

logger = get_logger(__name__)

# Встроенный HTML-шаблон (можно вынести в отдельный файл)
DEFAULT_HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Claster Forensic Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
        h2 { color: #34495e; margin-top: 30px; }
        table { border-collapse: collapse; width: 100%; margin: 20px 0; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #3498db; color: white; }
        .evidence { background-color: #f9f9f9; padding: 15px; border-left: 5px solid #e74c3c; }
        .footer { margin-top: 40px; font-size: 0.9em; color: #7f8c8d; text-align: center; }
    </style>
</head>
<body>
    <h1>Claster Forensic Report</h1>
    <p><strong>Case:</strong> {{ case_name }}</p>
    <p><strong>Examiner:</strong> {{ examiner }}</p>
    <p><strong>Generated:</strong> {{ timestamp }}</p>

    <h2>Executive Summary</h2>
    <p>{{ summary }}</p>

    <h2>Evidence Items</h2>
    <table>
        <tr><th>ID</th><th>Name</th><th>Hash (SHA-256)</th><th>Size</th></tr>
        {% for item in evidence %}
        <tr><td>{{ item.id }}</td><td>{{ item.name }}</td><td>{{ item.hash }}</td><td>{{ item.size }}</td></tr>
        {% endfor %}
    </table>

    {% if timeline %}
    <h2>Timeline</h2>
    <table>
        <tr><th>Timestamp</th><th>Source</th><th>Event</th></tr>
        {% for event in timeline %}
        <tr><td>{{ event.timestamp }}</td><td>{{ event.source }}</td><td>{{ event.description }}</td></tr>
        {% endfor %}
    </table>
    {% endif %}

    <h2>Chain of Custody</h2>
    <table>
        <tr><th>Date/Time</th><th>Action</th><th>Person</th><th>Notes</th></tr>
        {% for entry in custody %}
        <tr><td>{{ entry.timestamp }}</td><td>{{ entry.action }}</td><td>{{ entry.person }}</td><td>{{ entry.notes }}</td></tr>
        {% endfor %}
    </table>

    <div class="footer">
        <p>Report generated by Claster Forensic Toolkit - {{ version }}</p>
    </div>
</body>
</html>
"""

def generate_html_report(data: Dict[str, Any], output: str) -> None:
    """
    Generate an HTML report using Jinja2 templating.

    Args:
        data: Dictionary with report data (case_name, examiner, summary, evidence, timeline, custody).
        output: Path to output HTML file.
    """
    env = Environment(loader=FileSystemLoader('.'), autoescape=select_autoescape(['html']))
    template = env.from_string(DEFAULT_HTML_TEMPLATE)
    data.setdefault('timestamp', timestamp())
    data.setdefault('version', '1.0')
    html_content = template.render(**data)
    with open(output, 'w', encoding='utf-8') as f:
        f.write(html_content)
    logger.info(f"HTML report saved to {output}")

def generate_pdf_report(data: Dict[str, Any], output: str) -> None:
    """
    Generate a PDF report using ReportLab.
    """
    ensure_dir(Path(output).parent)
    doc = SimpleDocTemplate(output, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = styles['Title']
    story.append(Paragraph(f"Claster Forensic Report - {data.get('case_name', '')}", title_style))
    story.append(Spacer(1, 0.2*inch))

    # Metadata
    normal_style = styles['Normal']
    story.append(Paragraph(f"Examiner: {data.get('examiner', 'N/A')}", normal_style))
    story.append(Paragraph(f"Generated: {timestamp()}", normal_style))
    story.append(Spacer(1, 0.2*inch))

    # Summary
    story.append(Paragraph("Executive Summary", styles['Heading2']))
    story.append(Paragraph(data.get('summary', 'No summary provided.'), normal_style))
    story.append(Spacer(1, 0.2*inch))

    # Evidence table
    evidence = data.get('evidence', [])
    if evidence:
        story.append(Paragraph("Evidence Items", styles['Heading2']))
        table_data = [['ID', 'Name', 'Hash (SHA-256)', 'Size']]
        for item in evidence:
            table_data.append([item.get('id', ''), item.get('name', ''),
                               item.get('hash', ''), item.get('size', '')])
        t = Table(table_data)
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.grey),
            ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0,0), (-1,0), 12),
            ('GRID', (0,0), (-1,-1), 1, colors.black)
        ]))
        story.append(t)
        story.append(Spacer(1, 0.2*inch))

    # Chain of custody
    custody = data.get('custody', [])
    if custody:
        story.append(Paragraph("Chain of Custody", styles['Heading2']))
        table_data = [['Timestamp', 'Action', 'Person', 'Notes']]
        for entry in custody:
            table_data.append([entry.get('timestamp', ''), entry.get('action', ''),
                               entry.get('person', ''), entry.get('notes', '')])
        t = Table(table_data)
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.grey),
            ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
            ('GRID', (0,0), (-1,-1), 1, colors.black)
        ]))
        story.append(t)

    doc.build(story)
    logger.info(f"PDF report saved to {output}")

def generate_docx_report(data: Dict[str, Any], output: str) -> None:
    """
    Generate a DOCX report using python-docx.
    """
    doc = Document()
    doc.add_heading(f"Claster Forensic Report - {data.get('case_name', '')}", 0)
    doc.add_paragraph(f"Examiner: {data.get('examiner', 'N/A')}")
    doc.add_paragraph(f"Generated: {timestamp()}")

    doc.add_heading('Executive Summary', level=1)
    doc.add_paragraph(data.get('summary', 'No summary provided.'))

    evidence = data.get('evidence', [])
    if evidence:
        doc.add_heading('Evidence Items', level=1)
        table = doc.add_table(rows=1, cols=4)
        table.style = 'Light Shading Accent 1'
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'ID'
        hdr_cells[1].text = 'Name'
        hdr_cells[2].text = 'Hash (SHA-256)'
        hdr_cells[3].text = 'Size'
        for item in evidence:
            row_cells = table.add_row().cells
            row_cells[0].text = str(item.get('id', ''))
            row_cells[1].text = str(item.get('name', ''))
            row_cells[2].text = str(item.get('hash', ''))
            row_cells[3].text = str(item.get('size', ''))

    doc.save(output)
    logger.info(f"DOCX report saved to {output}")

def generate_csv_report(data: List[Dict[str, Any]], output: str) -> None:
    """Export data to CSV."""
    if not data:
        logger.warning("No data to export to CSV.")
        return
    ensure_dir(Path(output).parent)
    with open(output, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=data[0].keys())
        writer.writeheader()
        writer.writerows(data)
    logger.info(f"CSV report saved to {output}")

def generate_json_report(data: Any, output: str) -> None:
    """Export data to JSON."""
    ensure_dir(Path(output).parent)
    with open(output, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, default=str)
    logger.info(f"JSON report saved to {output}")

def add_timeline(report: Dict[str, Any], events: List[Dict]) -> Dict[str, Any]:
    """Add timeline data to a report dictionary."""
    report['timeline'] = events
    return report

def export_report_with_evidence(report: Dict[str, Any], evidence_dir: str) -> str:
    """
    Package the report along with all evidence files into a ZIP archive.
    Returns path to the created ZIP file.
    """
    import shutil
    import tempfile
    evidence_dir = Path(evidence_dir)
    if not evidence_dir.exists():
        logger.error(f"Evidence directory not found: {evidence_dir}")
        return ""
    # Create temp directory
    temp_dir = Path(tempfile.mkdtemp())
    report_file = temp_dir / "report.json"
    generate_json_report(report, str(report_file))
    # Copy evidence files
    for f in evidence_dir.iterdir():
        if f.is_file():
            shutil.copy2(f, temp_dir / f.name)
    # Create ZIP
    zip_name = f"report_evidence_{timestamp().replace(' ', '_').replace(':', '-')}"
    zip_path = temp_dir.parent / zip_name
    shutil.make_archive(str(zip_path), 'zip', temp_dir)
    shutil.rmtree(temp_dir)
    logger.info(f"Exported report with evidence to {zip_path}.zip")
    return str(zip_path) + ".zip"